# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11L1FC7PTO0DjICX0S9aACQQR4hCy7zWD
"""

import pandas as pd
df = pd.read_csv('/content/salaries.csv')
df.head()

inputs = df.drop('salary_more_then_100k',axis = 'columns')
target = df['salary_more_then_100k']
target

from sklearn.preprocessing import LabelEncoder

le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()
# converting the labels to the numbers

# creating the coloumns
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_company.fit_transform(inputs['job'])
inputs['degree_n'] = le_company.fit_transform(inputs['degree'])
inputs.head()

inputs_n = inputs.drop(['company','job','degree'], axis='columns')
inputs_n

from sklearn import tree

model = tree.DecisionTreeClassifier()

model.fit(inputs_n, target)

model.score(inputs_n, target)

model.predict([[2,0,2]])